version: v2
managed:
  enabled: true
  disable:
    - file_option: go_package
      module: buf.build/googleapis/googleapis
    - file_option: go_package
      module: buf.build/envoyproxy/protoc-gen-validate
    - file_option: go_package
      module: buf.build/kratos/apis
    - file_option: go_package
      module: buf.build/gnostic/gnostic
    - file_option: go_package
      module: buf.build/gogo/protobuf
    - file_option: go_package
      module: buf.build/tx7do/pagination
  override:
    - file_option: optimize_for
      value: SPEED
    - file_option: go_package_prefix
      value: kratos-cms/api/gen/go
plugins:
  - local: protoc-gen-openapi
    out: ../app/admin/service/cmd/server/assets
    opt:
      - naming=json
      - depth=2
      - default_response=false
      - enum_type=string
      - output_mode=merged
      - fq_schema_naming=false
